### PR TITLE
add back Domain::ipv{4,6}

### LINKED ISSUE #93: Braking change introduced by minor version 0.3.13
https://docs.rs/socket2/0.3.12/socket2/struct.Domain.html
https://docs.rs/socket2/0.3.13/socket2/struct.Domain.html

functions missing
`socket2::Domain::ipv4()`
`socket2::Domain::ipv6()`

### LINKED ISSUE #95: hyper build error
build error,detail message
```rust
error[E0599]: no function or associated item named `ipv4` found for struct `socket2::Domain` in the current scope
   --> /Users/baoyachi/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/http.rs:556:38
    |
556 |         SocketAddr::V4(_) => Domain::ipv4(),
    |                                      ^^^^ function or associated item not found in `socket2::Domain`

error[E0599]: no function or associated item named `ipv6` found for struct `socket2::Domain` in the current scope
   --> /Users/baoyachi/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/http.rs:557:38
    |
557 |         SocketAddr::V6(_) => Domain::ipv6(),
    |                                      ^^^^ function or associated item not found in `socket2::Domain`

error[E0599]: no function or associated item named `stream` found for struct `socket2::Type` in the current scope
   --> /Users/baoyachi/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/http.rs:559:44
    |
559 |     let socket = Socket::new(domain, Type::stream(), Some(Protocol::tcp()))?;
    |                                            ^^^^^^ function or associated item not found in `socket2::Type`

error[E0599]: no function or associated item named `tcp` found for struct `socket2::Protocol` in the current scope
   --> /Users/baoyachi/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/http.rs:559:69
    |
559 |     let socket = Socket::new(domain, Type::stream(), Some(Protocol::tcp()))?;
    |                                                                     ^^^ function or associated item not found in `socket2::Protocol`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `hyper`.
```

### PR DESCRIPTION
**Pull request by Keruspe**
This restores backward compatibility

Fixes #93
Fixes #95

### CODE REVIEW

**Comment by baoyachi** [comment]
How can this kind of mistake be avoided with use [https://semver.org/](https://semver.org/) in `cargo`?

**Comment by Keruspe** [comment]
@stjepang Could we get a quickfix 0.3.14?

**Comment by Keruspe** [comment]
> How can this kind of mistake be avoided with use https://semver.org/ in `cargo`?

semverver helps avoiding this kind of mistakes I think

**Comment by baoyachi** [comment]
Taking this event as an example, an hour has passed since the latest version of the update. Developers around the world have indirectly referenced the library, which has led to the failure of the project to compile normally. This control is not in the hands of developers, but in the authors who rely on the library, and the project control is lost。

**Comment by nevi-me** [comment]
@baoyachi semver depends on developer interpretation, so mistakes like this will happen once in a while. The changes that led to this issue seem to have been made around April, so without some external pre-release test from crates that depend on this one, I assume it would have been impossible to discover this issue until the new version was released.

**Comment by stjepang** [comment]
Published v0.3.14

**Comment by stjepang** [comment]
Really sorry about this! :( Let me know if this resolves the issue - I'll be online and respond promptly. You can also reach me on Discord if need be.

**Comment by nevi-me** [comment]
> Really sorry about this! :( Let me know if this resolves the issue - I'll be online and respond promptly. You can also reach me on Discord if need be.

No worries, it happens :)

It hasn't resolved the issue, there's now another one. 

```rust
error[E0599]: no function or associated item named `stream` found for struct `socket2::Type` in the current scope
   --> C:\Users\nevi\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.7\src\client\connect\http.rs:559:44
    |
559 |     let socket = Socket::new(domain, Type::stream(), Some(Protocol::tcp()))?;
    |                                            ^^^^^^ function or associated item not found in `socket2::Type`

error[E0599]: no function or associated item named `tcp` found for struct `socket2::Protocol` in the current scope
   --> C:\Users\nevi\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.7\src\client\connect\http.rs:559:69
    |
559 |     let socket = Socket::new(domain, Type::stream(), Some(Protocol::tcp()))?;
    |                                                                     ^^^ function or associated item not found in `socket2::Protocol`
```

**Comment by nevi-me** [comment]
Would it be safer to instead yank 0.3.13 and 0.3.14, and release the update as 0.4.0 @stjepang ?

**Comment by stjepang** [comment]
Ugh. Okay I'm going to yank this and postpone a new release until we figure this out.

**Pull request merged**
